

on:
  push:
    branches: ['main', 'master']
  pull_request:
    branches: ['main', 'master']

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
